name: td_remote_config
description: "Official Thinking RemoteConfig Flutter plugin. Used to get remote config data from Thinking Analytics."
version: 1.0.0
homepage: https://www.thinkingdata.cn

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
#  thinking_analytics:
#    path: ../flutter-sdk
  thinking_analytics: 3.3.1

flutter:
  plugin:
    platforms:
      android:
        package: cn.thinkingdata.tdremoteconfig_flutter
        pluginClass: TDRemoteConfigFlutterPlugin
      ios:
        pluginClass: TDRemoteConfigFlutterPlugin
